### ISSUE TITLE
no need for Log-Level INFO

### ISSUE THREAD

**Issue by greyslater** [stolk/chiaharvestgraph#18]
could you rewrite to use api and track the full round trip of farmer->harvester->farmer instead of parsing time from Log

**Comment by ppumkin** [comment]
Which API methods do you have in mind? Im not author but could have a look

**Comment by greyslater** [comment]
I really have no idea about coding but i stumbled across this together with https://github.com/felixbrucker/chia-dashboard-satellite and the associated dashboard because there's no need to change Log-Level to INFO

**Comment by ppumkin** [comment]
Ahh. I see what they doing. They still parse the logs but not from the log files.

The access the daemon through venv and query and do things via the CLI.
The CLI basically emits ALL logs relating to actions running.

I think the RPC API is still very limited in Chia.

I don’t think the CLI emits the data harvest graph needs directly.

On 21 May 2021, at 20:12, Christian Raab ***@***.***> wrote:

﻿

I really have no idea about coding but i stumbled across this together with https://github.com/felixbrucker/chia-dashboard-satellite and the associated dashboard because there's no need to change Log-Level to INFO
